# Generated by Django 3.2.9 on 2021-11-25 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=10)),
                ('adresse', models.EmailField(max_length=254)),
                ('nbParts', models.IntegerField()),
                ('motMairie', models.BooleanField()),
                ('carteDonnee', models.BooleanField()),
                ('presenceDistribution', models.DateField()),
                ('remarque', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('unite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('unitecat', models.IntegerField()),
                ('seuil_alerte', models.IntegerField()),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.categorie')),
            ],
        ),
    ]
