# Generated by Django 3.2.9 on 2021-11-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_cate_produit_cate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='nom',
            new_name='nomcate',
        ),
    ]
