# Generated by Django 3.2.9 on 2021-11-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='remarque',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
