# Generated by Django 3.2.9 on 2021-12-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_delete_beneficiaire2'),
    ]

    operations = [
        migrations.CreateModel(
            name='po',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fok', models.CharField(max_length=13)),
            ],
        ),
    ]
