# Generated by Django 3.2.9 on 2021-12-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_po'),
    ]

    operations = [
        migrations.DeleteModel(
            name='po',
        ),
    ]
