# Generated by Django 3.2.9 on 2021-11-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='cate',
            new_name='cate_id',
        ),
    ]
