# Generated by Django 3.2.9 on 2021-11-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_nom_categorie_nomcate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
