# Generated by Django 3.2.9 on 2021-11-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_beneficiaire_remarque'),
    ]

    operations = [
        migrations.DeleteModel(
            name='beneficiaire',
        ),
    ]
