# Generated by Django 3.2.9 on 2021-11-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20211127_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='beneficiaire',
        ),
    ]
