# Generated by Django 3.2.9 on 2021-11-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_beneficiaire_beneficiaire2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='beneficiaire2',
        ),
    ]
